import type { Metadata } from "next";
/* import { Geist, Geist_Mono } from "next/font/google"; */
import { Plus_Jakarta_Sans, Inter } from "next/font/google";
import "./globals.css";
import Analytics from "@/components/Analytics";

/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

const jakartaSans = Plus_Jakarta_Sans({
    variable: "--font-jakarta-sans",
    subsets: ["latin"],
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Tiago - Ideal para seu negócio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR">
            <body
                className={`${inter.variable} antialiased`}
            >
                {children}
            </body>
            <Analytics
                siteId={String(
                    process.env.NEXT_PUBLIC_SITE_ID
                )}
            />
        </html>
    );
}
